name: Build Debian Package
on: [push]

jobs:
  build-deb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run:  |
          cd install
          ./install_dependencies.sh
          pip install pyinstaller
          cd ..
        
      - name: Build Binary
        run: pyinstaller --onefile src/pcapdecoder.py --name "pcap_decoder"
      - name: Prepare .deb Structure
        run: |
          mkdir -p deb-package/usr/local/bin
          mkdir -p deb-package/DEBIAN
          ls
          ls dist/
          cp dist/pcap_decoder deb-package/usr/local/bin/
          
          echo "Package: pcap_decoder
          Version: 1.0.0
          Section: devel
          Priority: optional
          Homepage: https://github.com/usdot-fhwa-stol/pcapdecoder
          Architecture: amd64
          Maintainer: FHWA Saxton Laboratory <CARMAsupport@dot.gov>
          Description: RSU Tool for Decoding PCAP Files" > deb-package/DEBIAN/control
          
      - name: Build Debian Package
        run: dpkg-deb --build deb-package pcap_decoder.deb
        
      - name: Upload deb artifacts
        uses: actions/upload-artifact@v4
        with:
          name: deb-packages-x64-jammy
          path: |
            build*/_packages/*.deb
            ./build*/_packages/*.deb
  deb-s3-upload:
    runs-on: ubuntu-latest
    needs:
      -  build-deb
    container:
      image: ghcr.io/usdot-fhwa-stol/actions-deb-s3:main
    steps:
      - name: Publish deb artifacts
        uses: usdot-fhwa-stol/actions/deb-s3-upload@main
        with:
          artifact-name: deb-packages-x64-jammy
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          component-name: jammy